services:
  postgres:
    image: postgres:15.1
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: ./packages/backend
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
  
  web:
    container_name: react-app
    image: react-image
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - 3001:3000
